name: 'Enforce PR Rules'
description: 'Enforce PR rules for the repository'
inputs:
  release-branch-pattern:
    description: 'The pattern to match release branches'
    required: true
    default: 'release/*'
  feature-branch-pattern:
    description: 'The pattern to match feature branches'
    required: true
    default: 'feature/*'
  max-length:
    description: 'Max length of branch name. 0 means no limit'
    default: '0'

branding:
  icon: 'check-square'
  color: 'black'

runs:
  using: 'node20'
  main: 'dist/index.js'
